package homesplit.presentation;

import java.util.StringTokenizer;

/**
 *
 * @author Grupo 35
 */
public class DialogExceptions extends javax.swing.JDialog {

    /**
     * Creates new form DialogExceptions
     */
    public DialogExceptions(java.awt.Frame parent, boolean modal, String exception) {
        super(parent, modal);
        initComponents();
        exception = addLinebreaks(exception,40);
        String linhas[] = exception.split("\\r\\n|\\n|\\r");
        if(linhas.length == 2){
            ExceptionMessage.setText(linhas[0]);
            ExceptionMessage2.setText(linhas[1]);
        }
        else{
            ExceptionMessage.setText(exception);
        }
    }
    
    /**
     * Divide uma string em várias linhas de acordo com o tamanho especificado.
     */
    public static String addLinebreaks(String input, int maxLineLength) {
    String[] tokens = input.split("\\s+");
    StringBuilder output = new StringBuilder(input.length());
    int lineLen = 0;
    for (int i = 0; i < tokens.length; i++) {
        String word = tokens[i];

        if (lineLen + (" " + word).length() > maxLineLength) {
            if (i > 0) {
                output.append('\n');
            }
            lineLen = 0;
        }
        if (i < tokens.length - 1 && (lineLen + (word + " ").length() + tokens[i + 1].length() <=
                maxLineLength)) {
            word += " ";
        }
        output.append(word);
        lineLen += word.length();
    }
    return output.toString();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ExceptionMessage = new javax.swing.JLabel();
        ExceptionMessage2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ExceptionMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExceptionMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ExceptionMessage2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExceptionMessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExceptionMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExceptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ExceptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExceptionMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Fecha a janela.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExceptionMessage;
    private javax.swing.JLabel ExceptionMessage2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
