package homesplit.presentation;
import homesplit.business.GestaoDespesas.Despesa;
import homesplit.business.GestaoMoradores.Morador;
import javax.swing.*;
import homesplit.business.HomeSplit;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Grupo 35
 */
public class Frame extends javax.swing.JFrame {

    private HomeSplit homesplit;
    private static final int ALTURA_AVATAR = 162;
    private static final int LARGURA_AVATAR = 162;
    /**
     * Creates new form Frame
     */
    public Frame(HomeSplit homesplit) {
        initComponents();
        this.homesplit = homesplit;
        updateFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        avatar_principal = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        NomeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UsersList = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        NotificacoesList = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jButton13 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DespesasResponsavelList = new javax.swing.JList();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        DespesasList = new javax.swing.JList();
        jButton14 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        HistoricoDespesasList = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Muna", 1, 65)); // NOI18N
        jLabel1.setText(" HomeSplit");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homesplit/presentation/logo.png"))); // NOI18N

        avatar_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homesplit/presentation/icon.png"))); // NOI18N
        avatar_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        avatar_principal.setMaximumSize(new java.awt.Dimension(640, 960));
        avatar_principal.setMinimumSize(new java.awt.Dimension(640, 960));

        jButton4.setText("Sair do apartamento");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Validar registo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Editar perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton11.setText("Adicionar despesa");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        NomeLabel.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        NomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeLabel.setText("NOME DO USER");

        jLabel4.setText("Saldo:");

        SaldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SaldoLabel.setText("€");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(avatar_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(avatar_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(NomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SaldoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        NomeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(UsersList);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText(" Lista de notificações");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText(" Lista de utilizadores");

        jTextField1.setText("Search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        NotificacoesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(NotificacoesList);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jButton5.setText("Consultar notificações");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton13.setText("Consultar notificação");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(166, 166, 166)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234)
                        .addComponent(jButton5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addContainerGap())))
        );

        jScrollPane4.setViewportView(DespesasResponsavelList);

        jButton10.setBackground(new java.awt.Color(153, 221, 118));
        jButton10.setText("Liquidar despesa");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(153, 221, 118));
        jButton12.setText("Editar despesa");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton7.setText("Consultar despesa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homesplit/presentation/lixo2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10)
                        .addComponent(jButton12)
                        .addComponent(jButton7)))
                .addContainerGap())
        );

        jTabbedPane5.addTab("Despesas em que é responsável", jPanel5);

        jButton8.setBackground(new java.awt.Color(153, 221, 118));
        jButton8.setText("Pagar despesa");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(DespesasList);

        jButton14.setText("Consultar despesa");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 216, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton14))
                .addContainerGap())
        );

        jTabbedPane5.addTab("Despesas por pagar", jPanel4);

        jScrollPane5.setViewportView(HistoricoDespesasList);

        jButton6.setText("Consultar despesa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 336, Short.MAX_VALUE)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Histórico", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Actualiza a janela principal da aplicação.
     */
    public void updateFrame(){
        NomeLabel.setText(homesplit.getUtilizador().getNome());
        updateUsersList();
        updateDespesasResponsavelList();
        updateDespesasList();
        updateHistoricoDespesasList();
        updateNotificacoes();
        updateSaldo();
        updateAvatar();
    }
    
    /**
     * Actualiza o avatar do utilizador.
     */
    public void updateAvatar(){
        int largura, altura = 0;
        ImageIcon iconImagem;
        BufferedImage image = null;
        if(homesplit.getUtilizador().getAvatar()!=null){
            try{
                image = ImageIO.read(new File(homesplit.getUtilizador().getAvatar()));
                largura = image.getWidth();
                altura = image.getHeight();
                if(largura != LARGURA_AVATAR || altura != ALTURA_AVATAR){
                    iconImagem = new ImageIcon(image.getScaledInstance(LARGURA_AVATAR,ALTURA_AVATAR,Image.SCALE_SMOOTH));
                }
                else{
                    iconImagem = new ImageIcon(image);
                }
                avatar_principal.setIcon(iconImagem);
            }
            catch(Exception e){
                e.getMessage();
            }
        }
    }
    
    /**
     * Actualiza o saldo do utilizador.
     */
    public void updateSaldo(){
            SaldoLabel.setText(String.format( "%.2f",homesplit.getUtilizador().getSaldo())+" €");
    }
    
    /**
     * Actualiza a lista de utilizadores.
     */
    public void updateUsersList(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        Map<String,Morador> moradores = homesplit.getGestao_moradores().getListaMoradores();
        try{
            for(Map.Entry<String,Morador> entry : moradores.entrySet()){
                StringBuilder info = new StringBuilder();
                info.append("   " + entry.getValue().getNome());
                lista.addElement(info.toString());
            }
        }
        catch (Exception e){
            e.getMessage();
        }
        UsersList.setModel(lista); // ISTO FAZ APARECER UM WARNING!! 
    }
    
    /**
     * Actualiza a lista das despesas para as quais o utilizador é responsável.
     */
    public void updateDespesasResponsavelList(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        Map<Integer,Despesa> despesas = homesplit.consultarDespesasResponsavel();
        try{
            for(Despesa d : despesas.values()){
                lista.addElement(d.toString()+"   Valor Pago: "+d.getValor_pago_confirmado()+"€");
            }
        }
        catch (Exception e){
            e.getMessage();
        }
        DespesasResponsavelList.setModel(lista); // ISTO FAZ APARECER UM WARNING!! 
    }
    
    /**
     * Actualiza a lista das despesas para as quais o utilizador está incluido.
     */
    public void updateDespesasList(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        Map<Integer,Despesa> despesas = homesplit.consultarDespesas();
        
        try{
            for(Despesa d : despesas.values()){
                if(d.getFracao(homesplit.getUtilizador().getUsername()).temPrestacoes() && !(d.getFracao(homesplit.getUtilizador().getUsername()).prestacoesPagas())){
                    String m = d.toString() + d.getFracao(homesplit.getUtilizador().getUsername()).toString();
                    lista.addElement(m);
                }
                else if(!(d.getFracao(homesplit.getUtilizador().getUsername()).temPrestacoes())){
                    String m = d.toString() + d.getFracao(homesplit.getUtilizador().getUsername()).toString();
                    lista.addElement(m);
                }
            }
        }
        catch (Exception e){
            e.getMessage();
        }
        DespesasList.setModel(lista); // ISTO FAZ APARECER UM WARNING!! 
    }
    
    /**
     * Actualiza a lista das despesas que fazem parte do histórico.
     */
    public void updateHistoricoDespesasList(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        Map<Integer,Despesa> despesas = homesplit.consultarHistoricoDespesas();
        try{
            for(Despesa d : despesas.values()){
                lista.addElement(d.toString());
            }
        }
        catch (Exception e){
            e.getMessage();
        }
        HistoricoDespesasList.setModel(lista); // ISTO FAZ APARECER UM WARNING!! 
    }
    
    /**
     * Actualiza a lista das notificações do utilizador.
     */
    public void updateNotificacoes(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        List<String> not = homesplit.getUtilizador().getNotificacoes();
        for(String n : not){
            lista.addElement(n);
        }
        NotificacoesList.setModel(lista);
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    /**
     * Abre uma janela de confirmação para o utilizador abandonar o apartamento.
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // SAIR DO APARTAMENTO
        DialogSairApartamento sair_apartamento = 
                new DialogSairApartamento(this,true,homesplit);
        sair_apartamento.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    /**
     * Abre uma janela de confirmação para liquidar uma dada despesa.
     */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // LIQUIDAR DESPESA
        String despesa = (String)DespesasResponsavelList.getSelectedValue();
        if(despesa != null){
            despesa = despesa.substring(despesa.indexOf("(") + 1);
            despesa = despesa.substring(0, despesa.indexOf(")"));
            int id_despesa = Integer.parseInt(despesa);
            DialogLiquidarDespesa liquidar_despesa =
                    new DialogLiquidarDespesa(this,true,homesplit,id_despesa);
            liquidar_despesa.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed
    /**
     * Abre uma janela para editar o perfil do utilizador.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // EDITAR PERFIL
        DialogEditarPerfil editar_perfil = 
                new DialogEditarPerfil(this,true,homesplit);
        editar_perfil.setVisible(true);
        updateFrame();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Abre uma janela com as informações necessárias para adicionar uma despesa.
     */
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // ADICIONAR DESPESA
        DialogAdicionarDespesa adicionar_despesa = 
                new DialogAdicionarDespesa(this,true,homesplit);
        adicionar_despesa.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed
    /**
     * Abre uma janela de confirmação para terminar sessão.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TERMINAR SESSÃO
        DialogTerminarSessao terminar_sessao = 
                new DialogTerminarSessao(this,true,homesplit);
        terminar_sessao.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Abre uma janela de registos de utilizador.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // VALIDAR REGISTO
        DialogValidarRegisto validar_registo = 
                new DialogValidarRegisto(this,true,homesplit);
        validar_registo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Consulta o histórico das despesas.
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // CONSULTAR DESPESA HISTORICO(NÃO É DONO)
        String despesa = (String)HistoricoDespesasList.getSelectedValue();
        if(despesa != null){
            despesa = despesa.substring(despesa.indexOf("(") + 1);
            despesa = despesa.substring(0, despesa.indexOf(")"));
            int id_despesa = Integer.parseInt(despesa);
            DialogConsultarDespesa consultar_despesa = 
                    new DialogConsultarDespesa(this,true,homesplit,id_despesa);
            consultar_despesa.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    /**
     * Consulta as despesas para as quais o utilizador está incluido.
     */
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // CONSULTAR DESPESA (NÃO É DONO)
        if(DespesasList.getSelectedValue() != null){
            String despesa = (String) DespesasList.getSelectedValue().toString();
            despesa = despesa.substring(despesa.indexOf("(") + 1);
            despesa = despesa.substring(0, despesa.indexOf(")"));
            int id_despesa = Integer.parseInt(despesa);
            DialogConsultarDespesa consultar_despesa = 
                new DialogConsultarDespesa(this,true,homesplit,id_despesa);
            consultar_despesa.setVisible(true);
        }
    }//GEN-LAST:event_jButton14ActionPerformed
    /**
     * Abre uma janela de confirmação de pagamento de prestação de despesa.
     */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // PAGAR DESPESA
        if(DespesasList.getSelectedValue() != null){
            String despesa = (String)DespesasList.getSelectedValue().toString();
            despesa = despesa.substring(despesa.indexOf("(") + 1);
            despesa = despesa.substring(0, despesa.indexOf(")"));
            int id_despesa = Integer.parseInt(despesa);
            if(homesplit.prestacoesDefinidas(id_despesa)){
                DialogPagarDespesa pagar_despesa = new DialogPagarDespesa(this,true,homesplit,id_despesa);
                pagar_despesa.setVisible(true);
            }
            else{
                DialogPagarDespesaPrestacoes pagar_despesa_prestacoes = new DialogPagarDespesaPrestacoes(this,true,homesplit,id_despesa);
                pagar_despesa_prestacoes.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    /**
     * Abre uma janela para editar a despesa.
     */
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // EDITAR DEPESA
        if(DespesasResponsavelList.getSelectedValue() != null){
            String despesa = (String) DespesasResponsavelList.getSelectedValue().toString();
            despesa = despesa.substring(despesa.indexOf("(") + 1);
            despesa = despesa.substring(0, despesa.indexOf(")"));
            int id_despesa = Integer.parseInt(despesa);
            
            DialogEditarDespesa editar_despesa = 
                    new DialogEditarDespesa(this,true,homesplit,id_despesa);
            editar_despesa.setVisible(true);
        }
    }//GEN-LAST:event_jButton12ActionPerformed
    /**
     * Consulta a lista de despesas para as quais o utilizador é responsável.
     */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // CONSULTAR DESPESA
        String despesa = (String)DespesasResponsavelList.getSelectedValue();
        if(despesa != null){
            despesa = despesa.substring(despesa.indexOf("(") + 1);
            despesa = despesa.substring(0, despesa.indexOf(")"));
            int id_despesa = Integer.parseInt(despesa);
            DialogConsultarDespesaResponsavel consultar_despesa_responsavel = 
                new DialogConsultarDespesaResponsavel(this,true,homesplit,id_despesa);
            consultar_despesa_responsavel.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed
    /**
     * Abre uma janela de confirmação.
     */
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // APAGAR DESPESA
        String despesa = (String)DespesasResponsavelList.getSelectedValue();
        if(despesa != null){
            despesa = despesa.substring(despesa.indexOf("(") + 1);
            despesa = despesa.substring(0, despesa.indexOf(")"));
            int id_despesa = Integer.parseInt(despesa);
            DialogEliminarDespesa eliminar_despesa = new DialogEliminarDespesa(this,true,homesplit,id_despesa);
            eliminar_despesa.setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed
    /**
     * Consulta uma dada notificação.
     */
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(NotificacoesList.getSelectedValue() != null){
            String info = NotificacoesList.getSelectedValue().toString();
            DialogNotificacao notificacao = 
                    new DialogNotificacao(this,true,info);
            notificacao.setVisible(true);
        }
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList DespesasList;
    private javax.swing.JList DespesasResponsavelList;
    private javax.swing.JList HistoricoDespesasList;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JList NotificacoesList;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JList UsersList;
    private javax.swing.JLabel avatar_principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
